name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  checkout-and-build:
    runs-on: [ Windows, self-hosted ]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Generate Project
      shell: pwsh
      run: |
        .\GenerateProjects.bat
    - name: Build
      run: dotnet build --configuration Release
